version: '3.8'
services:
  postgresDB:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=nuvix_database_user
      - POSTGRES_PASSWORD=YBlSyUV3MJFZjbHLsu5Jm1aCv3j7DEje
      - POSTGRES_DB=nuvix_database
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  redisDB:
    image: redis:latest
    restart: always
    ports:
      - '6376:6379'